// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBri6klpZiGAbA2OPzGRhZ3eDZM8iBII90',
    appId: '1:935620278082:web:768cc9e9b1cabccda3fadb',
    messagingSenderId: '935620278082',
    projectId: 'ecommerce-da2d9',
    authDomain: 'ecommerce-da2d9.firebaseapp.com',
    storageBucket: 'ecommerce-da2d9.appspot.com',
    measurementId: 'G-8PVDZ76MPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHcHM8Q7exJKOFH46xs0d-SkJUAhz1PE',
    appId: '1:935620278082:android:a9fdf02d04bca947a3fadb',
    messagingSenderId: '935620278082',
    projectId: 'ecommerce-da2d9',
    storageBucket: 'ecommerce-da2d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFR0iD3JxtV4cOZKBfpPmOedY4ZLT1YrU',
    appId: '1:935620278082:ios:0c27be1eff7d8dbca3fadb',
    messagingSenderId: '935620278082',
    projectId: 'ecommerce-da2d9',
    storageBucket: 'ecommerce-da2d9.appspot.com',
    iosClientId: '935620278082-ikep8hpc5tg1sird7gqrs0kcv6eh7ss3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFR0iD3JxtV4cOZKBfpPmOedY4ZLT1YrU',
    appId: '1:935620278082:ios:0c27be1eff7d8dbca3fadb',
    messagingSenderId: '935620278082',
    projectId: 'ecommerce-da2d9',
    storageBucket: 'ecommerce-da2d9.appspot.com',
    iosClientId: '935620278082-ikep8hpc5tg1sird7gqrs0kcv6eh7ss3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
